import type { PermissionPreset } from '../types.js';
export const permissionPresets: PermissionPreset[] = [
  { key: 'firm-admin', title: 'Firm Admin', description: 'Manage all connectors, policies, and tools.', rules: [{ id: 'preset:firm-admin:allow-all', description: 'Firm admins can use all scaffold tools.', effect: 'allow' }] },
  { key: 'attorney', title: 'Attorney', description: 'Matter/document read access and ordinary matter work.', rules: [ { id: 'preset:attorney:read-and-work', description: 'Attorneys can search/read and create low/medium-risk items.', effect: 'allow', tools: { actions: ['search','read','create'], riskLevels: ['low','medium'] } }, { id: 'preset:attorney:confirm-writes', description: 'Attorney writes need confirmation when dry_run is false.', effect: 'allow', tools: { mutates: true }, obligations: { confirmationRequired: true } } ] },
  { key: 'paralegal', title: 'Paralegal', description: 'Assigned matter/task work; no exports/deletes by default.', rules: [ { id: 'preset:paralegal:read-matters', description: 'Paralegals can search/read matters.', effect: 'allow', tools: { actions: ['search','read'], resourceTypes: ['matter'] } }, { id: 'preset:paralegal:create-tasks-dry-run', description: 'Paralegals can preview task creation.', effect: 'allow', tools: { actions: ['create'], resourceTypes: ['task'], riskLevels: ['medium'] }, obligations: { dryRunRequired: true } }, { id: 'preset:paralegal:deny-dangerous', description: 'Paralegals cannot delete/export by default.', effect: 'deny', tools: { actions: ['delete','export'] } } ] },
  { key: 'intake', title: 'Intake', description: 'Lead/intake access.', rules: [{ id: 'preset:intake:read-low-risk', description: 'Intake can use low-risk read/search tools.', effect: 'allow', tools: { actions: ['search','read'], riskLevels: ['low'] } }] },
  { key: 'billing', title: 'Billing', description: 'Billing metadata access.', rules: [{ id: 'preset:billing:read-billing', description: 'Billing users can read billing resources.', effect: 'allow', tools: { resourceTypes: ['billing','invoice','payment'], actions: ['search','read'] } }] },
  { key: 'read-only', title: 'Read-only', description: 'Search/read only.', rules: [ { id: 'preset:read-only:allow-read', description: 'Read-only users can use read/search tools.', effect: 'allow', tools: { actions: ['search','read'] } }, { id: 'preset:read-only:deny-mutating', description: 'Read-only users cannot mutate data.', effect: 'deny', tools: { mutates: true } } ] }
];
export function rulesForPreset(presetKey: string) { return permissionPresets.find((p) => p.key === presetKey)?.rules ?? []; }
